spring.application.name=restaurant-backend

# PostgreSQL Database Configuration
# Base de datos: mr_panzo_db (Owner: postgres)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mr_panzo_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:6509}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
